config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'
  get '/home', to: 'pages#home'
  get '/term_of_use', to: 'pages#term_of_use'
  # get '/upload', to: 'microposts#upload'
  
  resources :microposts, only: [:new, :create, :destroy, :show]
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,  only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/upload', to: 'microposts#new'

  
  devise_for :users
  resources :users, only: [:show]
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/index', to: "users#index"
  
devise_scope :user do
  # Deviseのログイン画面をrootに設定
  root to: "devise/sessions#new"
  get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: :follower_id,
                                  dependent:  :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: :followed_id,
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites
  has_many :comments
  has_many :active_notifications, class_name: 'Notification', 
                                 foreign_key: 'visitor_id',
                                   dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification',
                                  foreign_key: 'visited_id',
                                    dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
         
  attr_writer :login

  def login
    @login || self.username || self.email
  end
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
  
  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: self.id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ?",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def profile_edit
 
  end
 
  def profile_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
	    redirect_to user_path(current_user.id), notice: 'プロフィールを更新しました'
    else
      render "profile_edit"
    end
  end
  
  protected
  
  def configure_account_update_params
   added_attrs = [:fullname, :username, :website, :profile, :telephone_number,
                  :sex]
   devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id]) 
    @microposts = @user.microposts
    
    # @micropost = @user.microposts
    # @comments = @micropost.comment
    @comment = Comment.new
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー中 / Unfollow", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
 <%= link_to user.fullname, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Users</h1>

<ul class = "users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, pages_show_path %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<% provide(:title, @user.fullname) %>

<h3><%= @user.fullname %>のプロフィール画面</h3>

<p>自己紹介　<%= @user.profile %> </p>

<!--　フォロワー数などここに表示-->
<%= render 'shared/stats' %>

<%= render 'follow_form' %>

<div>
  <% if @user.microposts.any? %>
  <h3>投稿数 <%= @user.microposts.count %> 件</h3>
  <ul>
    <%= render @microposts %>
  </ul>
  <% end %>
</div>

<% if current_user.id.to_s == params[:id] %>
  <%= link_to 'プロフィール編集', profile_edit_path %>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.fullname %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>