config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'
  get '/home', to: 'pages#home'
  get '/term_of_use', to: 'pages#term_of_use'
  # get '/upload', to: 'microposts#upload'
  
  resources :microposts, only: [:new, :create, :destroy, :show]
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,  only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/upload', to: 'microposts#new'

  
  devise_for :users
  resources :users, only: [:show]
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/index', to: "users#index"
  
devise_scope :user do
  # Deviseのログイン画面をrootに設定
  root to: "devise/sessions#new"
  get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
end
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol>
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', resource: f.object %>
  <div>
    <%= f.text_area :content, placeholder: "今何してる...?" %>
  </div>
  <%= f.submit "投稿" %>
  <span class = "picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_search.html.erb
<p>検索</p>
<%= form_tag(microposts_path, :method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class = "stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= @user.fullname %></h1>
<span><%= link_to "view my profile", @user %></span>
<!-- プロフィール画面に飛ぶ-->