config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'
  get '/home', to: 'pages#home'
  get '/term_of_use', to: 'pages#term_of_use'
  # get '/upload', to: 'microposts#upload'
  
  resources :microposts, only: [:new, :create, :destroy, :show]
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,  only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/upload', to: 'microposts#new'

  
  devise_for :users
  resources :users, only: [:show]
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/index', to: "users#index"
  
devise_scope :user do
  # Deviseのログイン画面をrootに設定
  root to: "devise/sessions#new"
  get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
end
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments, dependent: :destroy
  has_many :comment, class_name: "Comment",
                     foreign_key: :micropost_id
  has_many :notifications, dependent: :destroy
  
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true
  validate :picture_size
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(search)
    return Micropost.all unless search
    Micropost.where(['content LIKE ?', "%#{search}%"])
  end
  
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and micropost_id = ? and action = ? ",
                                current_user.id, user_id, id, 'like'])
    
    if temp.blank?
      notification = current_user.active_notifications.new(
        micropost_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(micropost_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end
  
  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、一つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      micropost_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private
  
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @user = User.find(current_user.id)
    # 空のmicropostをいれる
    @micropost = Micropost.new
  end
  
  #検索結果表示
  def index
    @feed_items = Micropost.search(params[:search])
    @comment = Comment.new
  end
  
  def create
    @user = User.find(current_user.id)
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      redirect_to root_url
    end
  end
  
  def show
    # 処理完了後、写真個別ページへリダイレクトする時や写真個別ページを表示させる時
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments
    @comment = Comment.new
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to root_url
  end
  
  def search
    @searched = Micropost.search(params[:search])
  end
  
  private
  
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
  
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id = "micropost-<%= micropost.id %>">
  <span><%= link_to micropost.user.fullname, micropost.user %></span>
  <span><%= micropost.content %></span>
  <%= image_tag micropost.picture.url if micropost.picture? %>
  <%= link_to micropost.content, micropost_path(micropost.id) %>
  <!-- 写真をリンク先としたい-->
  <% if micropost.favorited_by?(current_user) %>
    <p><%= link_to "お気に入りから削除", 
    micropost_favorites_path(micropost.id), method: :delete %></p>
  <% else %>
    <p><%= link_to "お気に入り登録",
    micropost_favorites_path(micropost.id), method: :post %></p>
  <% end %>
  <% micropost.comments.each do |c| %>
  <p><span>コメント内容: </span><%= c.body %></p>
<% end %>
</li>




<%= form_for([@micropost, @comment], url: micropost_comments_path(micropost.id), 
                                     method: :post) do |f| %>
  <%= f.text_field :body %>
  <%= f.submit "コメントする" %>
<% end %>
<!--<textarea cols="30" name="body" placeholder="コメント入力欄" rows="2"></textarea>-->
<!--<br/>-->
<!--<input type="submit" value="コメントする">-->

app/views/microposts/index.html.erb
<% if @feed_items.any? %>
  <ol>
    <%= render @feed_items %>
  </ol>
<% else %>
    <p> 検索結果ないよ！</p>
<% end %>

app/views/microposts/new.html.erb
<% provide(:title, '写真アップロード') %>
<h1>写真アップロード</h1>

<div>
  <aside>
    <section>
       <!--render 'shared/user_info' -->
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
</div>

app/views/microposts/show.html.erb
<h1>写真個別ページ</h1>
<p>投稿詳細:</p>
<%= image_tag @micropost.picture.url if @micropost.picture? %>
<%= @micropost.content %>

<h2>コメント一覧</h2>
<% @comments.each do |c| %>
  <p><span>コメント内容: </span><%= c.body %></p>
<% end %>

<%= form_for([@micropost, @comment], url: micropost_comments_path(@micropost.id), 
                                     method: :post) do |f| %>
  <%= f.text_field :body %>
  <%= f.submit "コメントする" %>
<% end %>
<% if current_user?(@micropost.user) %>
<%= link_to "delete", micropost_path(@micropost), method: :delete,
                      date: { confirm: "You sure?" } %>
<% end %>