config/routes.rb
Rails.application.routes.draw do

  get 'pages/show'
  get '/home', to: 'pages#home'
  get '/term_of_use', to: 'pages#term_of_use'
  # get '/upload', to: 'microposts#upload'
  
  resources :microposts, only: [:new, :create, :destroy, :show]
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
    resource :comments,  only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  
  get '/upload', to: 'microposts#new'

  
  devise_for :users
  resources :users, only: [:show]
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'users/index', to: "users#index"
  
devise_scope :user do
  # Deviseのログイン画面をrootに設定
  root to: "devise/sessions#new"
  get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
  patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
end
end

app/views/layouts/_footer.html.erb
<%= link_to '写真アップロード', upload_path %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to 'インスタグラム',     root_path %>
    <% if user_signed_in? %>
      <%= link_to '自分のプロフィール', current_user %>
      <%= link_to 'ログアウト',         destroy_user_session_path, method: :delete %>
      
      <% if unchecked_notifications.any? %>
        <%= link_to "通知あり", notifications_path %>
      <% else %>
        <%= link_to "通知なし", notifications_path %>
       <% end %>
    <% end %>
    <%= render "shared/search" %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>